### ISSUE TITLE
Feasibility

### ISSUE THREAD

**Issue by serkolch** [fizal619/rgb-invaders#1]
@fizal619 
Hey Fizal,

This idea is definitely interesting! As it is outside the scope of what we've learned in class, I just want to make sure that Melonjs is something you'll be able to work with. Please take today to work through a tutorial and see how it works.

As you have some comfort with coding and what we've done so far in class, I'm sure you should be comfortable trying to learn something on your own. If at the end of the day you decide it's too difficult, we can pivot to another, pared down game.

**Comment by fizal619** [comment]
@serkolch 
Finished with the "do over" of my proposal. I think I build on this from here and add more features and screens.

**Comment by fizal619** [comment]
@serkolch I believe this is resolved.

**Comment by serkolch** [comment]
...
